name: aer
description: "Aer - Weather Application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.0

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2 
  charts_flutter: ^0.11.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/windturbine_bg.png
    - lib/images/clouds_bg.png
    - lib/images/splash_screen_bg.png
    - lib/images/aer_logo.png
    - lib/images/cloud.png
    - lib/images/clouds.png
    - lib/images/mist.png
    - lib/images/sun.png
    - lib/images/storm.png
    - assets/.env
    - lib/images/storm_bg.png
    - lib/images/snow_bg.png
    - lib/images/rain.png